In [1]:
#import Libraries we need

import numpy as np 
import pandas as pd 

In [2]:
#imports data set into program
dataset = pd.read_csv('Iris.csv')

#Displays first 5 entries in data set so we can see if it's right
dataset.head()


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
x = dataset.iloc[:, 1:-1].values #Grabs all values from 1st column on left (1) and 1st column from right (-1)
y = dataset.iloc[:, -1].values #Grabs everything from last column on the right (-1)
print(x[:10])
print(y[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [4]:
from sklearn.model_selection import train_test_split

#train_test_split automatically splits the data into testing and training 
#training_test_split(rows, columns, %testing, random seed)

#Note: Random seed will produce same results when set to specific integer
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [5]:
#Scales the data so that they're all in standardized relative ranges (i.e so 2000m will be equal to 2km)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Note: fit_transform changes the scaler so that it can be applied to the data matrix. Once it's been fitted it doesn't have to be again
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

print(x_train[:10])

[[-1.88957244 -0.17112495 -1.47678423 -1.4017102 ]
 [-0.88180047  1.71715039 -1.01603907 -1.00686225]
 [ 0.88180047 -0.17112495  1.23009359  1.3622254 ]
 [-1.13374346 -1.58733146 -0.20973504 -0.21716637]
 [-1.13374346  0.06490946 -1.24641165 -1.4017102 ]
 [ 0.75582898 -0.40715937  0.36619642  0.17768157]
 [ 1.38568645  0.06490946  0.99972101  1.23060942]
 [-1.13374346 -1.35129704  0.48138271  0.7041455 ]
 [-0.1259715  -0.17112495  0.30860327  0.04606559]
 [-1.76360094  0.30094388 -1.36159794 -1.27009422]]


In [6]:
#Imports logistic regression model (what we'll be making from scratch)
from sklearn.linear_model import LogisticRegression

#Note: the multi_class = 'ovr' parameter allows for the logistic regression to be run for multiclass, will be blank if binary class
classifier = LogisticRegression(multi_class='ovr', random_state = 0)

classifier.fit(x_train, y_train) #Applies logistic regression to training data

LogisticRegression(multi_class='ovr', random_state=0)

In [7]:
#Tests How Accurate Our Model Was
from sklearn.metrics import confusion_matrix, accuracy_score
predictions = classifier.predict(x_test) #Creates predicted values via model
cm = confusion_matrix(predictions, y_test) #Creates confusion matrix for values
print(cm)
accuracy_score(predictions, y_test)

[[ 8  0  0]
 [ 0 10  1]
 [ 0  0 11]]


0.9666666666666667