In [29]:
#import Libraries we need

import numpy as np 
import pandas as pd 

In [30]:
#imports data set into program
dataset = pd.read_csv('Iris.csv')

#Displays first 5 entries in data set so we can see if it's right
dataset.head()


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [31]:
x = dataset.iloc[:, 1:-1].values #Grabs all values from 1st column on left (1) and 1st column from right (-1)
y = dataset.iloc[:, -1].values #Grabs everything from last column on the right (-1)
print(x[:10])
print(y[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [32]:
from sklearn.model_selection import train_test_split

#train_test_split automatically splits the data into testing and training 
#training_test_split(rows, columns, %testing, random seed)

#Note: Random seed will produce same results when set to specific integer
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

# Convert y-data into T/F - Note: "Iris-setosa" is T, rest are false
y_train = [ele == 'Iris-setosa' for ele in y_train]
y_test = [ele == 'Iris-setosa' for ele in y_test]

In [33]:
#Scales the data so that they're all in standardized relative ranges (i.e so 2000m will be equal to 2km)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Note: fit_transform changes the scaler so that it can be applied to the data matrix. Once it's been fitted it doesn't have to be again
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

print(x_train[:10])

[[-0.87884504  1.4576805  -1.27393083 -1.03741026]
 [ 1.27342852 -0.1304539   1.03008875  1.19499156]
 [ 0.38719823 -0.1304539   0.51168435  0.27576728]
 [-1.25865802  0.77705147 -1.04352887 -1.30004576]
 [ 2.41286747 -0.58420658  1.72129463  1.06367381]
 [-1.76507533 -0.35733024 -1.33153132 -1.30004576]
 [-1.13205369 -1.49171195 -0.23712202 -0.24950373]
 [-1.00544937 -0.1304539  -1.21633034 -1.30004576]
 [ 0.64040689  0.77705147  1.08768924  1.58894482]
 [ 0.13398958  0.32329879  0.62688533  0.8010383 ]]


In [34]:
#Imports logistic regression model (what we'll be making from scratch)
from sklearn.linear_model import LogisticRegression

#Note: the multi_class = 'ovr' parameter allows for the logistic regression to be run for multiclass, will be blank if binary class
classifier = LogisticRegression(random_state = 0)

classifier.fit(x_train, y_train) #Applies logistic regression to training data

LogisticRegression(random_state=0)

In [35]:
#Tests How Accurate Our Model Was
from sklearn.metrics import confusion_matrix, accuracy_score
predictions = classifier.predict(x_test) #Creates predicted values via model
cm = confusion_matrix(predictions, y_test) #Creates confusion matrix for values
print(cm)
accuracy_score(predictions, y_test)

[[21  0]
 [ 0  9]]


1.0