In [36]:
#import Libraries we need

import numpy as np 
import pandas as pd 

In [37]:
#imports data set into program
dataset = pd.read_csv('../DataSets/Iris.csv')

#Displays first 5 entries in data set so we can see if it's right
dataset.head()


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [38]:
x = dataset.iloc[:, 1:-1].values #Grabs all values from 1st column on left (1) and 1st column from right (-1)
y = dataset.iloc[:, -1].values #Grabs everything from last column on the right (-1)
print(x[:10])
print(y[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [39]:
from sklearn.model_selection import train_test_split

#train_test_split automatically splits the data into testing and training 
#training_test_split(rows, columns, %testing, random seed)

#Note: Random seed will produce same results when set to specific integer
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

# Convert y-data into T/F - Note: "Iris-setosa" is T, rest are false
y_train = [ele == 'Iris-virginica' for ele in y_train]
y_test = [ele == 'Iris-virginica' for ele in y_test]

In [40]:
#Scales the data so that they're all in standardized relative ranges (i.e so 2000m will be equal to 2km)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Note: fit_transform changes the scaler so that it can be applied to the data matrix. Once it's been fitted it doesn't have to be again
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

print(x_train[:10])

[[-0.22662448 -0.52680829  0.35328362  0.08150698]
 [ 0.96613596 -0.08161819  0.75376708  1.42134773]
 [ 0.72758387 -0.08161819  1.09703862  1.28736365]
 [-0.10734844 -0.74940334  0.12443593 -0.32044525]
 [-0.94228075  1.03135708 -1.42028599 -1.39231784]
 [-0.34590053 -1.19459345  0.01001209 -0.18646117]
 [ 0.96613596 -0.08161819  0.63934324  0.61744328]
 [ 0.36975574 -0.52680829  0.52491939  0.75142735]
 [ 0.25047969 -0.08161819  0.58213132  0.75142735]
 [-0.10734844  2.14433234 -1.53470983 -1.39231784]]


In [41]:
#Imports logistic regression model (what we'll be making from scratch)
from sklearn.linear_model import LogisticRegression

#Note: the multi_class = 'ovr' parameter allows for the logistic regression to be run for multiclass, will be blank if binary class
classifier = LogisticRegression(random_state = 0)

classifier.fit(x_train, y_train) #Applies logistic regression to training data

LogisticRegression(random_state=0)

In [42]:
#Tests How Accurate Our Model Was
from sklearn.metrics import confusion_matrix, accuracy_score
predictions = classifier.predict(x_test) #Creates predicted values via model
cm = confusion_matrix(predictions, y_test) #Creates confusion matrix for values
print(cm)
accuracy_score(predictions, y_test)

[[23  0]
 [ 0  7]]


1.0